FROM centos:7

# cenntosにnginxのリポジトリを登録(これがないとインストールに失敗する)
COPY ./nginx.repo /etc/yum.repos.d/nginx.repo
RUN yum install -y nginx

# ドキュメントルート
ADD ./app /usr/share/nginx/html
ADD ./nginx.conf /etc/nginx/nginx.conf:ro

# 待ち受けポート番号
EXPOSE 80

# フォアグラウンドで実行しないとコンテナが停止してしまう
CMD nginx -g "daemon off;"